<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
JHtml::_('bootstrap.tooltip');
JHtml::_('behavior.framework');

// Create a shortcut for params.
$params  = & $this->item->params;
$images  = json_decode($this->item->images);
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

$aInfo1 = ($params->get('show_publish_date') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author'));
$aInfo2 = ($params->get('show_create_date') || $params->get('show_modify_date') || $params->get('show_hits'));
$topInfo = ($aInfo1 && $info != 1) || ($aInfo2 && $info == 0);
$botInfo = ($aInfo1 && $info == 1) || ($aInfo2 && $info != 0);
$icons = $params->get('access-edit') || $params->get('show_print_icon') || $params->get('show_email_icon');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

// update catslug if not exists - compatible with 2.5
if (empty ($this->item->catslug)) {
  $this->item->catslug = $this->item->category_alias ? ($this->item->catid.':'.$this->item->category_alias) : $this->item->catid;
}
?>

<?php foreach($this->item->jcfields as $jcfield)
     {
          $this->item->jcfields[$jcfield->name] = $jcfield;
     }
?>

<?php JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php'); ?>

<?php foreach ($this->item->jcfields as $field) : ?>

	<?php //echo FieldsHelper::render($field->context, 'field.render', array('field' => $field)); ?>
<?php endforeach ?>

<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate() )) : ?>
<div class="system-unpublished">
<?php endif; ?>

	<!-- Article -->
	<article>
  <div class="item-detail">
    <?php if ($params->get('show_title')) : ?>
      <?php echo JLayoutHelper::render('joomla.content.item_title', array('item' => $this->item, 'params' => $params, 'title-tag'=>'h2')); ?>
      <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
    <?php endif; ?>
	
    <?php if (!$params->get('show_intro')) : ?>
      <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
      <?php echo $this->item->event->afterDisplayTitle; ?>
    <?php endif; ?>

    <!-- Aside -->
    <?php if ($topInfo || $icons) : ?>
    <aside class="article-aside clearfix">
      <?php if ($topInfo): ?>
      <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
      <?php endif; ?>
      
      <?php if ($icons): ?>
      <?php echo JLayoutHelper::render('joomla.content.icons', array('item' => $this->item, 'params' => $params)); ?>
      <?php endif; ?>
    </aside>  
    <?php endif; ?>
    <!-- //Aside -->

		<section class="article-intro clearfix">
      <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
			<?php echo $this->item->event->beforeDisplayContent; ?>

<div class="row">	


    <div class="col-sm-7">
    <?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
</div>
<div class="col-sm-5">
<?php // CAMPOS PERSONALIZADOS ?>
<?php if($this->item->jcfields['precio']->value) {?>
<h4 class="<?php echo $this->item->jcfields['precio']->name; ?>"><?php echo $this->item->jcfields['precio']->value; ?></h4>
<?php } ?>
<?php if($this->item->jcfields['talles']->value) {?>
<h4 class="<?php echo $this->item->jcfields['talles']->name; ?>"><strong><?php echo $this->item->jcfields['talles']->name; ?>:</strong> <?php echo $this->item->jcfields['talles']->value; ?></h4>
<?php } ?>
<div class="colores">
  <h4>Colores</h4>
<?php  if ($this->item->jcfields['colores']){
	if(is_array($this->item->jcfields['colores']->rawvalue)){
       
$colores = explode(',',$this->item->jcfields['colores']->value);
$p = 0;

foreach ($this->item->jcfields['colores']->rawvalue as $item) {


  echo'<div class="panel "> <div class="panel-heading" style="background-color:'.$item.'"> &nbsp; </div> <div class="panel-body"> '.$colores[$p].'</div> </div>';

  
 $p++;
}
	}if(is_string($this->item->jcfields['colores']->rawvalue)){



    echo'<div class="panel "> <div class="panel-heading" style="background-color:'.$this->item->jcfields['colores']->rawvalue.'"> &nbsp; </div> <div class="panel-body"> '.$this->item->jcfields['colores']->value.'</div> </div>';

	//	echo '<div  class="label" style="background-color:'.$this->item->jcfields['colores']->rawvalue.'">'.$this->item->jcfields['colores']->value.'</div>';	
		
	}} 
?>
<jdoc:include type="modules" name="consultas" style="none" />
</div>

</div>
    		<?php //echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
</div>
<hr/>

<div class="text-detail">	<?php echo $this->item->text; ?></div>
</div>






		
		</section>

    <!-- footer -->
    <?php if ($botInfo) : ?>
    <footer class="article-footer clearfix">
      <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
      <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
    </footer>
    <?php endif; ?>
    <!-- //footer -->


		<?php if ($params->get('show_readmore') && $this->item->readmore) :
			if ($params->get('access-view')) :
				$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
			else :
				$menu      = JFactory::getApplication()->getMenu();
				$active    = $menu->getActive();
				$itemId    = $active->id;
        $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
        $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
			endif; ?>

      <?php echo JLayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
      
		<?php endif; ?>

	</article>
	<!-- //Article -->

<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
</div>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?> 
